{
    "name":"Dealer Sales Memo",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description": """
        Dealer Sales Memo
    """,
    "depends":[
        "product",
        "account",
        "account_voucher",
        "dym_branch",
        "dym_faktur_pajak",
        "dym_program_subsidi",
        "dym_res_partner_cddb",
        "dym_serial_number",
        "dym_stock",
        "dym_proses_stnk",
    ],
    "data":[       
        "report/kuitansi_cod.xml",        
        "report/report_dealer_so_lampiran.xml",    
        "report/report_dealer_so.xml",            
        "report/report_dealer_spk.xml",            
        "report/report_barcode.xml",            
        "report/report_surat_kuasa.xml",
        "report/report_kuitansi_pembalik.xml",
        "report/report_kuitansi_mediator.xml",            
        "report/report_invoice.xml",            
        "report/report_penagihan_leasing.xml",            
        "report/dso_report.xml",            
        "wizard/dealer_sale_order_report_wizard.xml",
        "views/dealer_spk_report_vew.xml",
        "views/customer_invoice_view.xml",                   
        "views/dealer_sale_order_report.xml",
        "views/dealer_sale_order_view.xml",
        "views/dealer_sale_order_workflow.xml",
        "views/dealer_spk_view.xml",
        "views/dym_serial_number_view.xml",
        "views/dym_branch_config_view.xml",
        "views/dealer_register_spk_view.xml",
        "views/dealer_generate_register_spk_view.xml",
        "views/dealer_distribusi_spk_view.xml",
        "views/dealer_pengembalian_spk_view.xml",
        "views/dealer_approval_sale_order_view.xml",
        "views/dym_on_outgoing_shipments.xml",
        "data/dym_approval_config_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        # "security/res_groups.xml",
        # "security/res_groups_button.xml",
    ],
    "qweb" : [
        "static/src/xml/dealer_spk_report.xml"
    ],
    "active":False,
    "installable":True
}