{
    "name":"DYM Advance Payment",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description": """
        Advance Payment
    """,
    "depends":[
        "base",
        "account",
        "dym_branch",
        "dym_approval",
        "dym_dealer_menu",
        "dym_account_filter",
        "dym_base_security",
        "dym_pettycash",
        "dym_bank_transfer",
        "dym_ahass",
        "dym_report_custom",
        "dym_account_voucher",
    ],
    "data":[
        "views/dym_advance_payment_report.xml",
        "views/dym_advance_payment_view.xml",
        "views/dym_approval_advance_payment_view.xml",
        "views/dym_settlement_view.xml",
        "views/dym_approval_settlement_view.xml",
        "views/dym_advance_payment_workflow.xml",
        "views/dym_settlement_workflow.xml",
        "views/dym_branch_config_view.xml",
        "security/ir.model.access.csv",
        "data/dym_approval_config_data.xml",
        # "security/res_groups.xml",
        "security/ir_rule.xml",
        "views/dym_advance_payment_ib_view.xml",
        "views/dym_reimbursed_ho_view.xml",
        "views/dym_reimbursed_advance_payment_view.xml",
        "views/dym_transaction_withholding_view.xml",
        "views/dym_settlement_withholding_view.xml",
        "views/dym_bank_transfer_view.xml",
        "report/dym_advance_payment_done_report.xml",
        "report/dym_advance_payment_draft_report.xml",
        "report/dym_settlement_done_report.xml",
        "report/dym_settlement_draft_report.xml",
        "report/dym_reimbursed_settlement_report.xml",
    ],
    "active":False,
    "installable":True
}
