{
    "name":"Petty Cash",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description": """
        PettyCash Out
    """,
    "depends":[
        "base",
        "account",
        "dym_dealer_menu",
        "dym_approval",
        "dym_branch",
        "dym_account_filter",
        "dym_account_move",
        "dym_work_order",
        "dym_base_security",
        # "dym_report_custom",
    ],
    "data":[
        "views/dym_petty_cash_out_report.xml",
        "views/dym_petty_cash_in_report.xml",
        "views/dym_reimbursed_pc_report.xml",
        "views/dym_pettycash_out_workflow.xml",
        "views/dym_pettycash_out_view.xml",
        "views/dym_pettycash_in_view.xml",
        "views/dym_reimbursed_view.xml",
        "views/dym_approval_pettycash_out_workflow.xml",
        "views/dym_approval_pettycash_out_view.xml",
        "views/report_pettycashin.xml",
        "views/report_reimbursedpc.xml",
        # "data/ir.sequence.xml",
        # "data/account.journal.xml",
        "data/dym_approval_config_data.xml",
        "data/petty_cash_full_refund_reason.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml", 
        # "security/res_groups.xml",        
        # "security/res_groups_button.xml", 
        "views/account_view.xml",
        "views/dym_branch_config_view.xml",
        "views/report_pettycashout.xml",
        "views/dym_petty_cash_in_full_refund_view.xml",
        "wizard/fully_return_reason.xml",
    ],
    "active":False,
    "installable":True
}