{
    "name":"Purchase Order",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description":"Purchase Order",
    "depends":[
        "base",
        "account",
        "purchase",
        "purchase_requisition",
        "dym_branch",
        "dym_account_voucher",
        "dym_approval",
        "dym_sequence",
        "dym_close_purchase",
        "dym_dealer_menu",
        "dym_account",
        "dym_loan",
        "dym_ranking",
    ],
    "data":[
        "report/report_po.xml",
        "report/po_report.xml",
        "wizard/distribute_discount_view.xml",
        "views/dym_purchase_order_report.xml",
        "views/dym_purchase_order_view.xml",
        "views/dym_approval_po_view.xml",
        "views/dym_approval_po_workflow.xml",
        "views/dym_purchase_order_type_view.xml",
        "views/dym_branch_config_view.xml",
        "views/dym_purchase_order_type_data.xml",
        "views/dym_account_invoice_view.xml",
        # "dym_incoming_shipments_showroom.xml",
        # "dym_incoming_shipments_workshop.xml",
        "views/dym_on_incoming_shipments_showroom.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        # "security/res_groups.xml",
        # "security/res_groups_button.xml",
        # "data/ir.sequence.xml",
        # "data/dym.branch.config.xml"
        "data/dym_approval_config_data.xml",            
    ],
    "active":False,
    "installable":True
}