{
    "name":"DYM Security",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description": """
        Security Access & Groups
    """,
    "depends":[
        "base",
        "dym_branch",
        "dym_stock_account",
        "dym_asset_disposal",
        "dym_purchase_asset",
        "dym_retur_beli",
        "dym_retur_jual",
        "dym_loan",
        "dym_ranking",
        "dym_proposal_event",
        "dym_work_days",
        "dym_stock_taking",
        "dym_permohonan_faktur",
        "stock",
        "dym_approval",
        "account_asset",
        "dym_product",
        "dym_pricelist",
        "account_voucher",
        "purchase",
        "sale",
        "dym_scheduled_actions",
    ],
    "data":[            
        # "res.groups.csv",
        # "ir.model.access.csv",
    ],
    "active":False,
    "sequence":1000,
    "installable":True
}