{
    "name":"Journal Eliminasi",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description":"Journals",
    "depends":[
        "base",
        "account",
        "dym_branch",
        "dym_account_move",
        "dym_eksport_import",
        "dym_journal_consolidation",
        "dym_purchase_order",
        "dym_sale_order",
        "dealer_sale_order",
        "dym_bank_in_out",

    ],
    "data":[
        "views/dym_res_company_view.xml",
        "views/dym_journal_eliminasi_view.xml",
        "views/dym_approval_journal_eliminasi_view.xml",
        "views/dym_intercompany_ref_view.xml",
        "views/dym_purchase_order_view.xml",
        "views/dym_sale_order_view.xml",
        "views/dealer_sale_order_view.xml",
        "views/dym_account_voucher_view.xml",
        "wizard/dym_report_intercompany_view.xml",
        "security/ir.model.access.csv",
        "data/dym_approval_config_data.xml",
        "data/ir_sequence.xml",                 
        # "security/res_groups.xml",
        # "security/res_groups_button.xml", 
    ],
    "active":False,
    "installable":True
}
