{
    "name":"Work Order",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description": """
    Addons Work Order:
    - Form Work Order
    - Picking Slip (generated on confirm work order)
    - Clocking Work Order (start & stop)
    - Customer Invoice (generated on validate work order)
    """,
    "depends":[
        "base",
        "hr",
        "account",
        "dym_faktur_pajak",
        "dym_branch",
        "dym_account",
        "dym_sequence",
        "dym_dealer_menu",
        "dym_serial_number",
        "dealer_sale_order"
    ],
    "data":[
        "report/report_bast_kpbclaim.xml",
        "report/report_pkb_kecil.xml",
        "report/report_kwitansi_kecil.xml",
        "report/report_njb.xml",
        "report/report_nsc.xml",
        "report/report_pkb.xml",
        "report/report_invoice.xml",
        "report/work_order_report.xml",
        "wizard/dym_work_order_wip_view.xml",
        "views/dym_work_order_wip_report.xml", 
        "views/dym_work_order_report.xml",
        "views/dym_work_order_view.xml",
        "views/dym_kpb_expired_view.xml",                  
        "views/dym_start_stop_wo_view.xml",
        "views/dym_production_stock_lot_view.xml",
        "views/dym_collecting_kpb_view.xml",
        "views/dym_approval_wo_view.xml",
        "views/dym_kpb_engine_type_view.xml",
        "views/dym_harga_jasa_view.xml",
        "views/dym_collecting_kpb_workflow.xml",
        "views/dym_work_order_workflow.xml",
        "views/dym_branch_config_data.xml",
        "views/dym_pit.xml",
        "views/dym_check_revisit.xml",
        "wizard/dym_frt_wiz.xml",
        "views/dym_frt.xml",
        "security/ir.model.access.csv",
        # "security/res_groups.xml",
        "security/ir_rule.xml",
        # "report/work_order_report_view.xml",
        # "data/dym.kpb.engine.type.csv",
        # "data/dym.kpb.engine.price.csv",
        # "data/dym.kpb.expired.xml",
        # "data/dym.workshop.category.csv",
        # "data/product.product.csv",
        "data/product.category.csv",
        # "data/dym.harga.jasa.csv",
        "data/ir.sequence.xml",
        # "data/product.product.xml",
        # "data/dym.branch.config.xml",
        # "data/dym.workshop.category.xml",
        # "data/dym.kpb.engine.type.xml",
        # "data/dym.kpb.engine.price.xml",
        # "data/dym.kpb.expired.xml",
        # "data/dym.harga.jasa.xml",
        "data/dym_approval_config_data.xml",
        "data/dym.days.revisit.xml",
    ],
    "installable":True,
    "active":False,
}

