{
    "name":"DYM Bank Transfer",
    "version":"1.0",
    "author":"ADSOFT",
    "category":"Custom Module for DYMS",
    "description": """
        Bank Transfer
    """,
    "depends":[
        "base",
        "dym_branch",
        "account",
        "dym_account_move",
        "dym_pettycash",
        "account_voucher",
        "dym_account_voucher",
        "dym_clearing_giro",
    ],
    "data":[  
        "wizard/account_transfer_from_voucher_view.xml",
        "wizard/generate_lines_view.xml",
        "wizard/confirm_received_view.xml",
        "wizard/multi_internet_banking.xml",
        "wizard/export_internet_banking.xml",
        "wizard/ibanking_done_view.xml",
        "views/dym_bank_transfer_report_view.xml",
        "report/dym_bank_transfer_report.xml",
        "report/dym_bank_transfer_ho_to_branch_report.xml",
        "report/dym_ibanking_report.xml",
        "data/dym_approval_config_data.xml",
        "views/dym_bank_transfer_workflow.xml",   
        "views/dym_approval_bank_transfer_workflow.xml", 
        "views/dym_bank_transfer_view.xml",   
        "views/dym_approval_bank_transfer_view.xml",
        "views/dym_branch_config_view.xml",  
        "views/dym_bank_statement_view.xml",
        "views/dym_checkgyro_view.xml",
        "views/account_voucher_view.xml",
        "views/dym_approval_account_voucher_view.xml",
        "views/res_partner_bank_view.xml",
        "views/account_journal_view.xml",
        "views/dym_ibanking_view.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
    ],
    "active":False,
    "installable":True
}